WalkiePaw/walkie-paw

src/main/java/com/WalkiePaw/web/ConfigFilter.java, src/main/java/com/WalkiePaw/web/filter/AuthCheckFilter.java
=> Feat: Filter 적용

src/main/java/com/WalkiePaw/domain/entity/BaseEntity.java, src/main/java/com/WalkiePaw/domain/entity/Board.java, src/main/java/com/WalkiePaw/domain/entity/BoardStatus.java, src/main/java/com/WalkiePaw/domain/entity/Member.java, src/main/java/com/WalkiePaw/domain/entity/MemberStatus.java
member, board 엔티티 구현해봤습니다. 아직 다 만들지는 않았는데 어떤 식으로 구현하는지 참고하시면 좋을 것 같아요
어떤 변경 사항이 있나요?
=> member board entity 구현 (미완)

src/main/java/com/WalkiePaw/domain/entity/board/BoardPhoto.java, src/main/java/com/WalkiePaw/domain/entity/chatV1/ChatMessage.java, src/main/java/com/WalkiePaw/domain/entity/chatV1/ChatMessageStatus.java, src/main/java/com/WalkiePaw/domain/entity/chatV1/ChatPhoto.java, src/main/java/com/WalkiePaw/domain/entity/chatroom/Chatroom.java, src/main/java/com/WalkiePaw/domain/entity/notification/Notification.java, src/main/java/com/WalkiePaw/domain/entity/qna/Qna.java, src/main/java/com/WalkiePaw/domain/entity/report/BoardReport.java, src/main/java/com/WalkiePaw/domain/entity/report/BoardReportCategory.java, src/main/java/com/WalkiePaw/domain/entity/report/MemberReport.java, src/main/java/com/WalkiePaw/domain/entity/report/MemberReportCategory.java
=> 38 feat entity 기본생성자 및 create method 생성

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepository.java, src/main/java/com/WalkiePaw/domain/chat/chatV1/entity/ChatMessage.java, src/main/java/com/WalkiePaw/domain/chat/chatV1/entity/ChatMessageStatus.java, src/main/java/com/WalkiePaw/domain/chat/chatV1/entity/ChatPhoto.java, src/main/java/com/WalkiePaw/domain/chat/chatV2/entity/ChatMessage.java, src/main/java/com/WalkiePaw/domain/chat/chatV2/entity/ChatMessageStatus.java, src/main/java/com/WalkiePaw/domain/chat/chatV2/entity/ChatPhoto.java, src/main/java/com/WalkiePaw/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/WalkiePaw/domain/chatroom/ChatroomRepository.java, src/main/java/com/WalkiePaw/domain/report/repository/BoardReportRepository.java, src/main/java/com/WalkiePaw/domain/report/repository/MemberReportRepository.java
board, chat, chatroom, report Repository 구현
어떤 변경 사항이 있나요?
=> Feat: repository 구현

src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/qna/entity/Qna.java, src/main/java/com/WalkiePaw/domain/report/entity/BoardReport.java, src/main/java/com/WalkiePaw/domain/report/entity/MemberReport.java, src/main/java/com/WalkiePaw/domain/review/entity/Review.java
=> Feat: Entity Builder 추가

src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepository.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/domain/qna/repository/QnaRepository.java, src/main/java/com/WalkiePaw/domain/qna/service/QnaService.java, src/main/java/com/WalkiePaw/domain/report/repository/BoardReportRepository.java, src/main/java/com/WalkiePaw/domain/report/repository/MemberReportRepository.java, src/main/java/com/WalkiePaw/domain/report/service/BoardReportService.java, src/main/java/com/WalkiePaw/domain/report/service/MemberReportService.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaRequest.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaResponse.java, src/main/java/com/WalkiePaw/presentation/domain/report/BoardReportController.java, src/main/java/com/WalkiePaw/presentation/domain/report/MemberReportController.java, src/main/java/com/WalkiePaw/presentation/domain/report/boardReportDto/BoardReportRequest.java, src/main/java/com/WalkiePaw/presentation/domain/report/memberReportDto/MemberReportRequest.java, src/main/java/com/WalkiePaw/presentation/domain/report/memberReportDto/MemberReportResponse.java
- Transactional 추가
- DTO 변경
- memberReport contoller,service repository 구현
어떤 변경 사항이 있나요?
=> Fix: Service Transactional 추가, DTO 변경

src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/domain/report/entity/BoardReport.java, src/main/java/com/WalkiePaw/domain/report/service/BoardReportService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberAddRequest.java, src/main/resources/application.properties
=> Feat: Swagger 적용 테스트

build.gradle, src/main/java/com/WalkiePaw/domain/chat/repository/ChatMsgRepository.java, src/main/java/com/WalkiePaw/domain/chat/repository/ChatMsgRepositoryImpl.java, src/main/java/com/WalkiePaw/domain/chat/repository/SpringDataChatMsgRepository.java, src/main/java/com/WalkiePaw/domain/chat/service/ChatService.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java, src/main/java/com/WalkiePaw/presentation/domain/chat/ChatController.java, src/main/resources/application.properties
- Board List Response 보낼 때 게시글 상태갑 추가
- chatMsg 벌크성 업데이트 기능 추가
어떤 변경 사항이 있나요?
=> Feat: BoardListDto, ChatMsg 벌크 업데이트 추가

src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardStatusUpdateRequest.java, src/main/java/com/WalkiePaw/presentation/domain/chat/ChatController.java
- Board Update Status 구현
어떤 변경 사항이 있나요?
=> Feat: Board Update Status 구현

src/main/java/com/WalkiePaw/domain/qna/repository/JpaQnaRepositoryImpl.java, src/main/java/com/WalkiePaw/domain/qna/repository/SpringDataQnaRepository.java, src/main/java/com/WalkiePaw/domain/report/repository/JpaBoardReportRepositoryImpl.java, src/main/java/com/WalkiePaw/domain/report/repository/JpaMemberReportRepositoryImpl.java, src/main/java/com/WalkiePaw/domain/report/repository/SpringDataBoardReportRepository.java, src/main/java/com/WalkiePaw/domain/report/repository/SpringDataMemberReportRepository.java
- fetch join을 통한 db 쿼리 단축
- EntityGraph를 통한 db 쿼리 단축
어떤 변경 사항이 있나요?
=> 76 feat fetch join을 통한 db 쿼리 단축

src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java
board category 추가
어떤 변경 사항이 있나요?
=> Feat: board category 추가

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberScoreResponse.java
한 멤버의 리뷰 평점을 응답해주는 기능 구현
어떤 변경 사항이 있나요?
=> 81 feat 한 멤버의 리뷰 평점을 응답해주는 기능 구현

src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberRRCountResponse.java
한 멤버의 구인 구직 각각의 횟수를 응답하는 기능 구현
어떤 변경 사항이 있나요?
=> Feat: 한 멤버의 구인 구직 각각의 횟수를 응답하는 기능 구현

src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberPasswdUpdateRequest.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberUpdateRequest.java
회원 정보 업데이트와 회원 암호 업데이트 분리
어떤 변경 사항이 있나요?
=> Fix: 회원 정보 업데이트와 회원 암호 업데이트 분리

build.gradle, src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/domain/board/entity/BoardStatus.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/resources/application.properties
- board delete 구현
- board category 필드 수정
어떤 변경 사항이 있나요?
=> Feat: board delete 구현

src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/global/exception/BadRequestException.java, src/main/java/com/WalkiePaw/global/exception/ExceptionCode.java, src/main/java/com/WalkiePaw/global/exception/ExceptionResponse.java, src/main/java/com/WalkiePaw/global/exception/GlobalExceptionHandler.java
- exception handler를 모아두는 GlobalExceptionHandler 클래스 생성
- 요청 코드를 모아서 관리할 수 있는 enum 클래스인 ErrorCode 클래스 생성
- boardService의 예외 처리 변경
- error 코드를 반환하는 dto인 ErrorResponse 생성
어떤 변경 사항이 있나요?
=> Feat: exception handler 구현

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepository.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardSearchRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardStatusUpdateRequest.java, src/main/resources/application.properties
search 컨트롤러, 서비스, 리포지토리 추가
어떤 변경 사항이 있나요?
=> Feat: search 구현

build.gradle, src/main/java/com/WalkiePaw/config/SecurityConfig.java, src/main/java/com/WalkiePaw/domain/member/Repository/JpaMemberRepositoryImpl.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepository.java, src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/security/AuthController.java, src/main/java/com/WalkiePaw/security/CustomUserDetailService.java, src/main/java/com/WalkiePaw/security/JwtAuthenticationFilter.java, src/main/java/com/WalkiePaw/security/JwtDecoder.java, src/main/java/com/WalkiePaw/security/JwtIssuer.java, src/main/java/com/WalkiePaw/security/JwtToPrincipalConverter.java, src/main/java/com/WalkiePaw/security/TestController.java, src/main/java/com/WalkiePaw/security/UserPrincipal.java, src/main/java/com/WalkiePaw/security/UserPrincipalAuthenticationToken.java, src/main/java/com/WalkiePaw/security/dto/LoginRequest.java, src/main/java/com/WalkiePaw/security/dto/LoginResponse.java, src/main/resources/application.properties
로그인 및 회원가입 기능 구현
어떤 변경 사항이 있나요?
=> 92 feat 로그인 및 회원가입 기능 구현

src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaListResponse.java
qna list response에 qnaId, memberId 추가
어떤 변경 사항이 있나요?
=> 103 qnagetresponse = qna 번호 회원 번호 memberid 관리자 페이지용 추가

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java
- memberController에 withDraw 추가.
회원 탈퇴 추가
어떤 변경 사항이 있나요?
=> Feat: 회원 탈퇴 추가

src/main/java/com/WalkiePaw/config/SecurityConfig.java, src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/security/CustomPasswordEncoder.java, src/main/java/com/WalkiePaw/security/TestController.java
- 회원가입 시 패스워드 암호화 처리
- 비밀번호 변경시 패스워드 암호화 처리
어떤 변경 사항이 있나요?
=> Feat: 회원가입 시 패스워드 암호화 처리 구현

src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberListResponse.java
=> Feat: MemberListResposne에 createdDate 추가

src/main/java/com/WalkiePaw/presentation/domain/upload/UploadController.java, src/main/java/com/WalkiePaw/presentation/domain/upload/UploadService.java
AWS S3에 업로드 후 URL 받아오는 것까지 구현
어떤 변경 사항이 있나요?
=> Feat: S3 업로드 구현

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java
transactional 처리
어떤 변경 사항이 있나요?
=> Refactor: transactional 처리

src/main/java/com/WalkiePaw/domain/qna/entity/Qna.java, src/main/java/com/WalkiePaw/domain/qna/service/QnaService.java, src/main/java/com/WalkiePaw/presentation/domain/qna/QnaController.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/replyUpdateRequest.java
QnaGetResponse에 qnaId 추가 및 qnaReplyUpdate 추가
어떤 변경 사항이 있나요?
=> Feat: QnaGetResponse에 qnaId 추가 및 qnaReplyUpdate 추가

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/review/service/ReviewService.java, src/main/java/com/WalkiePaw/global/util/Querydsl4RepositorySupport.java, src/main/java/com/WalkiePaw/presentation/domain/review/ReviewController.java, src/main/java/com/WalkiePaw/presentation/domain/review/TransactionRequest.java, src/main/java/com/WalkiePaw/presentation/domain/upload/UploadController.java
=> Refactor: util refactoring

src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/domain/board/entity/BoardPhoto.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardPhotoRepository.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/chatroom/service/ChatroomService.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardUpdateRequest.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/ChatroomController.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/dto/TransactionResponse.java, src/main/java/com/WalkiePaw/presentation/domain/upload/UploadController.java
board photo 적용, dto들도 다 수정
어떤 변경 사항이 있나요?
=> Feat: board photo 적용

src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/dto/TransactionResponse.java, src/main/java/com/WalkiePaw/presentation/domain/upload/UploadController.java
transaction query 수정
어떤 변경 사항이 있나요?
=> Fix: transaction query 수정

src/main/java/com/WalkiePaw/domain/mail/service/MailService.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepository.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/mail/EmailController.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/FindEmailRequest.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/FindEmailResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/FindPasswdRequest.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/FindPasswdResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/FindPasswdResult.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/NCheckResult.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/NicknameCheckResponse.java
닉네임 중복확인이메일비밀번호 찾기
어떤 변경 사항이 있나요?
=> 136 feat 닉네임 중복확인이메일비밀번호 찾기

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/global/util/Querydsl4RepositorySupport.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java
board pagination 적용
어떤 변경 사항이 있나요?
=> Feat: board pagination 적용

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardUpdateRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/ImageDto.java
=> Fix: photo

src/main/java/com/WalkiePaw/domain/board/entity/Board.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardLikeRepository.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/board/service/BoardLikeService.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/global/util/Querydsl4RepositorySupport.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardLikeController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardLikeAddRequest.java
board like add 추가, slice support 수정
어떤 변경 사항이 있나요?
=> Feat: board like add 추가

src/main/java/com/WalkiePaw/domain/board/repository/BoardLikeRepository.java, src/main/java/com/WalkiePaw/domain/board/service/BoardLikeService.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardLikeController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardLikeRequest.java
board like cancel 처리
어떤 변경 사항이 있나요?
=> Feat: board like cancel 처리

build.gradle, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/global/config/ChatWebSocketHandler.java, src/main/java/com/WalkiePaw/global/config/WebSocketConfig.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java
=> Fix: list 수 정

src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/chatroom/service/ChatroomService.java, src/main/java/com/WalkiePaw/domain/review/repository/ReviewRepository.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/ChatroomController.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/dto/TransactionResponse.java
=> 155 feat  chat

src/main/java/com/WalkiePaw/global/util/Querydsl4RepositorySupport.java
=> Fix: board list 수정

src/main/java/com/WalkiePaw/global/config/ChatWebSocketHandler.java, src/main/java/com/WalkiePaw/global/config/WebSocketConfig.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java
=> Fix: member photo

src/main/java/com/WalkiePaw/security/AuthController.java, src/main/java/com/WalkiePaw/security/TestController.java, src/main/java/com/WalkiePaw/security/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/WalkiePaw/security/jwt/service/JwtService.java, src/main/java/com/WalkiePaw/security/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
- 로그인 요청 경로 /api/v1/auth/login으로 수정
- TestController
로그인 관련 버그 수정
어떤 변경 사항이 있나요?
=> Fix: 로그인 관련 버그 수정

src/main/java/com/WalkiePaw/security/UserPrincipal.java, src/main/java/com/WalkiePaw/security/jwt/filter/JwtAuthenticationProcessingFilter.java, src/main/java/com/WalkiePaw/security/jwt/service/JwtService.java, src/main/java/com/WalkiePaw/security/login/handler/LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/login/service/LoginService.java, src/main/java/com/WalkiePaw/security/oauth/CustomOAuth2User.java, src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/service/CustomOAuth2UserService.java
- token의 ID 클레임 명을 id로 변경
- token에 nickname 클레임 추가
- CustomOAuth2USer, UserPrincipal memberId 데이터 타입 변경 Long -> Integer
어떤 변경 사항이 있나요?
=> Fix: 로그인 관련 코드 수정

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/EmailCheckResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/EmailCheckResult.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/NCheckResult.java, src/main/java/com/WalkiePaw/security/jwt/filter/JwtAuthenticationProcessingFilter.java
=> Fix: 이메일 중복 검사 추가

src/main/java/com/WalkiePaw/security/oauth/CustomOAuth2User.java, src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/service/CustomOAuth2UserService.java
소셜 로그인 시 응답 포맷 변경
```
Account Status:
Name:
Email:
Token:
```
어떤 변경 사항이 있나요?
=> Fix: 소셜 로그인 시 응답 포맷 변경

src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/domain/qna/repository/QnaRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/qna/repository/QnaRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/qna/service/QnaService.java, src/main/java/com/WalkiePaw/global/exception/ExceptionCode.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/ProfileResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/SocialSignUpRequest.java, src/main/java/com/WalkiePaw/presentation/domain/qna/QnaController.java, src/main/resources/application.properties
아래의 요청 핸들러 생성
- 마이페이지 - 비밀번호 변경
- 마이페이지 - 나의 문의 리스트
- 프로파일(대시보드) - 이름, 이미지, 소개글
- 회원가입 - 소셜 로그인 회원가입
어떤 변경 사항이 있나요?
=> 170 feat 요청 핸들러 생성

src/main/java/com/WalkiePaw/config/SecurityConfig.java
- cors allow method post -> patch
CORS 설정 변경
어떤 변경 사항이 있나요?
=> Fix: CORS 설정 변경

src/main/java/com/WalkiePaw/domain/member/entity/Role.java, src/main/resources/application.properties
멤버 Role에 admin 추가
어떤 변경 사항이 있나요?
=> Fix: 멤버 Role에 admin 추가

src/main/java/com/WalkiePaw/security/UserPrincipal.java, src/main/java/com/WalkiePaw/security/jwt/service/JwtService.java, src/main/java/com/WalkiePaw/security/login/handler/LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/login/service/LoginService.java, src/main/java/com/WalkiePaw/security/oauth/CustomOAuth2User.java, src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/service/CustomOAuth2UserService.java
토큰에 포토 url 포함시키기
어떤 변경 사항이 있나요?
=> Feat: 토큰에 포토 url 포함시키기

src/main/java/com/WalkiePaw/domain/member/entity/Member.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/AddressesGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberGetResponse.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberUpdateRequest.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/UpdateSelectedAddrRequest.java
=> 183 feat 게시판 리스트에서 사용될 사용자의 집 주소 + 선택된 주소를 응답해주는 핸들러 생성

src/main/java/com/WalkiePaw/security/oauth/userInfo/KakaoOAuth2UserInfo.java
카카오 소셜 로그인 버그 수정
어떤 변경 사항이 있나요?
=> Fix: 카카오 소셜 로그인 버그 수정

src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java
소셜 로그인 응답값에 토큰 미포함 버그 수정
어떤 변경 사항이 있나요?
=> Fix: 소셜 로그인 응답값에 토큰 미포함 버그 수정

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/SideBarInfoResponse.java
마이페이지 좌측 사이드 사용자 데이터 응답해주는 핸들러 생성
어떤 변경 사항이 있나요?
=> Feat: 마이페이지 좌측 사이드 사용자 데이터 응답해주는 핸들러 생성

src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/global/exception/ExceptionCode.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/ProfileResponse.java
=> 196 fix 프로파일 정보 요청 변경

src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/board/service/BoardService.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepository.java, src/main/java/com/WalkiePaw/global/exception/BindingErrorResponse.java, src/main/java/com/WalkiePaw/global/exception/ExceptionCode.java, src/main/java/com/WalkiePaw/global/exception/GlobalExceptionHandler.java, src/main/java/com/WalkiePaw/presentation/domain/board/BoardController.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/board/dto/BoardListResponse.java, src/main/java/com/WalkiePaw/presentation/domain/chat/dto/ChatAddRequest.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/dto/ChatroomListResponse.java, src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/service/CustomOAuth2UserService.java
=> Feat: chatroomlistresponse 수정

src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/domain/report/repository/BoardReport/BoardReportRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/report/repository/BoardReport/BoardReportRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/report/repository/MemberReport/MemberReportRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/report/repository/MemberReport/MemberReportRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/report/service/BoardReportService.java, src/main/java/com/WalkiePaw/domain/report/service/MemberReportService.java, src/main/java/com/WalkiePaw/presentation/domain/member/MemberController.java, src/main/java/com/WalkiePaw/presentation/domain/member/dto/MemberListResponse.java, src/main/java/com/WalkiePaw/presentation/domain/report/BoardReportController.java, src/main/java/com/WalkiePaw/presentation/domain/report/MemberReportController.java, src/main/java/com/WalkiePaw/presentation/domain/report/boardReportDto/BoardReportListResponse.java, src/main/java/com/WalkiePaw/presentation/domain/report/memberReportDto/MemberReportListResponse.java
관리자 페이지 페이징 처리
관리자 페이지의 회원 리스트, 회원 신고 리스트, 게시글 신고 리스트 페이징 처리 완료
어떤 변경 사항이 있나요?
=> 195 feat 관리자 페이지 페이징 처리

src/main/java/com/WalkiePaw/domain/qna/repository/QnaRepositoryOverride.java, src/main/java/com/WalkiePaw/domain/qna/repository/QnaRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/domain/qna/service/QnaService.java, src/main/java/com/WalkiePaw/presentation/domain/qna/QnaController.java, src/main/java/com/WalkiePaw/presentation/domain/qna/dto/QnaListResponse.java
- 관리자 페이지 문의 리스트 페이징 처리
- 마이페이지 문의 리스트 페이징 처리
어떤 변경 사항이 있나요?
=> Feat: 문의 리스트 페이징 처리

.gitignore, src/main/java/com/WalkiePaw/domain/mail/service/MailService.java, src/main/java/com/WalkiePaw/domain/member/service/MemberService.java, src/main/java/com/WalkiePaw/domain/qna/service/QnaService.java, src/main/java/com/WalkiePaw/domain/report/service/BoardReportService.java, src/main/java/com/WalkiePaw/domain/report/service/MemberReportService.java, src/main/java/com/WalkiePaw/global/exception/ExceptionCode.java, src/main/java/com/WalkiePaw/global/exception/MailException.java, src/main/java/com/WalkiePaw/presentation/domain/mail/dto/EmailAuthResponse.java
fix exception 처리
- memberReport exception 처리
- boardRerpot exception 처리
- qnaService  exception 처리
- memberService exception 처리
- 
어떤 변경 사항이 있나요?
=> 199 fix exception 처리

src/main/java/com/WalkiePaw/domain/member/Repository/MemberRepository.java
- 관리자는 로그인할 수 없는 버그 수정
어떤 변경 사항이 있나요?
=> Fix: 관리자 로그인 버그 수정

src/main/java/com/WalkiePaw/security/jwt/service/JwtService.java, src/main/java/com/WalkiePaw/security/login/handler/LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/WalkiePaw/security/oauth/userInfo/GoogleOAuth2UserInfo.java
JWT 토큰에 role 추가
어떤 변경 사항이 있나요?
=> Feat: JWT 토큰에 role 추가

src/main/java/com/WalkiePaw/presentation/domain/member/dto/ProfileResponse.java
대시보드 정보 응답에 memberId 추가
어떤 변경 사항이 있나요?
=> Fix: 대시보드 정보 응답에 memberId 추가

src/main/java/com/WalkiePaw/domain/board/repository/BoardLikeRepository.java, src/main/java/com/WalkiePaw/domain/board/repository/BoardRepository.java, src/main/java/com/WalkiePaw/domain/chatroom/repository/ChatroomRepositoryOverrideImpl.java, src/main/java/com/WalkiePaw/presentation/domain/chatroom/dto/ChatroomListResponse.java
=> Feat: chat

.github/workflows/deploy.yml, Dockerfile, build.gradle, src/main/java/com/WalkiePaw/WalkiePawApplication.java, src/main/java/com/WalkiePaw/utils/YamlPropertySourceFactory.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
- deploy.yml, Docekrfile 추가
- properties - dev, prod로 분리
어떤 변경 사항이 있나요?
=> 215 배포 main에 적용하기

Dockerfile
=> Fix: 컨테이너에서 redis 설치하도록 변경
